[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

# This ensures proper routing for the single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200