[build]
  publish = "dist"
  command = "npm run build"

# Force JavaScript MIME type
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=43200"  # Cache for 12 hours

# Set cache control for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Set cache control for version.json 
[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Set longer cache for static assets that have hashed names
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache for 1 year

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200