[build]
  publish = "dist"
  command = "npm run build"

# Force JavaScript MIME type
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200